### ISSUE TITLE
Task Assigment

### ISSUE THREAD

**Issue by dotieuthien** [incenger/cinai_colorization#1]

**Comment by khoa3101** [comment]
@khoa3101 
- Data preprocessing
- Correspondence subnet
- Loss function:
  + Perceptual loss
  + Contextual loss
  + Smoothless loss

@incenger 
- Colorization subnet
- Discriminator
- Loss function:
  + Adversarial loss
  + Temporal consistency loss
  + L1 loss

**Comment by dotieuthien** [comment]
Nice. hmmmmmm @incenger theo anh hieu la minh se ko can discriminator dau em, do minh la anh anime chu khong phai natural scene. Neu em dung thi em phai modify lai cho hop li. @khoa3101 tui em xem xet lai thu xem.

**Comment by khoa3101** [comment]
Tại ban đầu em đọc 1 bài báo tô màu cho manga người ta có dùng discriminator với adversarial loss nên em nghĩ là có lí do họ mới xài

**Comment by dotieuthien** [comment]
@khoa3101 em gui paper qua slack cua channel nhe, anh review thu xem
